### PR TITLE
348 add deep linking to controls

### PR DESCRIPTION
**Pull request by vanessuniq**
- Each control is wrapped in a hyperlink element that opens in a new tab. We can also select a control without clicking on the link.
- Alternatively, we can add a link icon to each control and wrap it in a hyperlink element.

image

### CODE REVIEW

**Comment by freddyfeelgood** [comment]
Initial testing looks good. One minor "bug" is in the URL, if you change the component ID, but leave the rest, it will navigate you to the control in the new component with the same last 6 digits (looks like the "prefix" isn't being checked).
So for example, if I am at location:
http://127.0.0.1:3000/components/97/controls/HZNV-8X-000021
And I change to component 103:
http://127.0.0.1:3000/components/103/controls/HZNV-8X-000021
It loads the page, but the control is actually PHTN-30-000021 (in this example).
Clicking another control in the project and coming back to PHTN-30-000021 then refreshes the URL correctly.

**Comment by freddyfeelgood** [comment]
More issues found... for example, unlocking a control doesn't refresh the screen. Then when changing the status, the other mandatory fields don't change like they're supposed to. Also, if typing into a field, then nagivating to another control, the text in the field doesn't change as expected.

**Comment by smarlaku820** [comment]
Hi @vanessuniq ,

I love the way I can get to any control by performing a GET.
observed a lot going in the backend. lot of queries. 

If I click, 4 or 5 controls on the page, its even getting delayed in loading the page & hitting the performance. Can we do something to cache the responses ? And did you observe this pattern at your end ?

**Comment by vanessuniq** [comment]
> Hi @vanessuniq ,
> 
> I love the way I can get to any control by performing a GET. observed a lot going in the backend. lot of queries.
> 
> If I click, 4 or 5 controls on the page, its even getting delayed in loading the page & hitting the performance. Can we do something to cache the responses ? And did you observe this pattern at your end ?

Yes, I noticed that. I did not want to change the workflow that was already in place, just build on top of it. This is due to several event listener within all involved Rules vue components that triggers axios. This workflow definitely needs to be optimized.

**Comment by vanessuniq** [comment]
Moving this to draft, continue working on the issues

**Comment by vanessuniq** [comment]
resolved with pr #546

**Pull request closed without merging**
