### PR TITLE
VULCAN-138: Ability to start new revision of STIG

### PR DESCRIPTION
**Pull request by timwongj**
Closes: https://github.com/mitre/vulcan/issues/138

### CODE REVIEW

**Comment by rlakey** [comment]
@timwongj not sure if the deployment needs redone but getting this error when trying to the copy component workflow as admin

**Comment by timwongj** [comment]
> @timwongj not sure if the deployment needs redone but getting this error when trying to the copy component workflow as admin
> 
> image

Redeployed, let me know if it still doesn't work!

**Comment by timwongj** [comment]
> 

@rlakey these should be addressed now

**Comment by rlakey** [comment]
Confirmed the comments/history copying over.  I probably won't be able to effectively test the SRG update part in the test environment so I can try that out once I update my environment.

**Pull request merged**
